
-- Insert all service types including existing ones
INSERT INTO service_types (code, name, is_active, display_order) VALUES
('VISTO_ESTUDANTE', 'Visto Estudante', true, 1),
('VISTO_TRABALHO', 'Visto Trabalho', true, 2),
('REAGRUPAMENTO', 'Reagrupamento Familiar', true, 3),
('RENOVACAO_RESIDENCIA', 'Renovação de Residência', true, 4),
('NACIONALIDADE_RESIDENCIA', 'Nacionalidade por Residência', true, 5),
('NACIONALIDADE_CASAMENTO', 'Nacionalidade por Casamento', true, 6),
('AUTORIZACION_REGRESO', 'Autorización de Regreso', true, 10),
('TIE_HUELLAS', 'Tarjeta de Identidad de Extranjero (TIE) - toma de huellas', true, 11),
('CERT_RESIDENTE_NO_RESIDENTE', 'Certificado de Residente o no Residente', true, 12),
('NIE_EUROPEOS', 'Certificado de Registro de ciudadano de la UE (NIE Europeos)', true, 13),
('CERT_CONCORDANCIA', 'Certificado de Concordancia', true, 14),
('CERT_NACIMIENTO_MATRIMONIO', 'Certificado de Nacimiento, Matrimonio, Defunción, Fe y Vida y de Fe de Estado (Inscritos en Brasil) – Traducidos y apostillados', true, 15),
('ANTECEDENTES_BRASIL', 'Certificado de antecedentes penales (en Brasil)', true, 16),
('CANCELACION_ANTECEDENTES_ES', 'Cancelación de Antecedentes penales (en España)', true, 17),
('ANTECEDENTES_ESPANA', 'Certificado de Antecedentes penales (en España)', true, 18),
('MATRIMONIO_CIVIL', 'Matrimonio Civil', true, 19),
('INSCRIPCION_MATRIMONIO_EXT', 'Inscripción de matrimonio civil celebrado en el extranjero', true, 20),
('BAJA_PAREJA', 'Baja de pareja', true, 21),
('NIE', 'Número de Identidad de Extranjero (NIE)', true, 22),
('RENOVACION_PASAPORTE', 'Renovación de pasaporte', true, 23),
('CANJE_CARNET_CONDUCIR', 'Canje de Carnet de conducir', true, 24),
('RECURSO_ADMINISTRATIVO', 'Recurso administrativo', true, 25),
('ESTANCIA_INVESTIGACION', 'Autorización de Estancia para investigación o formación', true, 26),
('ESTANCIA_PRACTICAS_NL', 'Autorización de Estancia por Prácticas No-Laborables', true, 27),
('HOMOLOGACION_SUPERIOR', 'Homologación Educación Superior', true, 28),
('HOMOLOGACION_NO_UNIVERSITARIO', 'Homologación de títulos No Universitarios', true, 29),
('PRORROGA_ESTANCIA_ESTUDIOS', 'Prórroga de Estancia por Estudios', true, 30),
('RESIDENCIA_NO_LUCRATIVA', 'Autorización Inicial de Residencia No Lucrativa', true, 31),
('RESIDENCIA_NO_LUCRATIVA_FAMILIAR', 'Autorización Inicial de Residencia No Lucrativa para Familiar', true, 32),
('RENOVACION_NO_LUCRATIVA', 'Renovación de Residencia No Lucrativa', true, 33),
('REAGRUPACION_FAMILIAR', 'Autorización de Residencia por Reagrupación Familiar', true, 34),
('RENOVACION_REAGRUPACION', 'Renovación de Residencia por Reagrupación Familiar', true, 35),
('TRABAJO_CUENTA_AJENA_ESTUDIOS', 'Autorización Trabajo por Cuenta Ajena para titulares de estancia por estudios', true, 36),
('RESIDENCIA_TRABAJO_AJENA_ORIGEN', 'Autorización Inicial de Residencia y Trabajo por Cuenta Ajena desde el país de origen', true, 37),
('RESIDENCIA_TRABAJO_AJENA', 'Autorización Inicial de Residencia y Trabajo por Cuenta Ajena', true, 38),
('RENOVACION_TRABAJO_AJENA', 'Renovación de Residencia y Trabajo por Cuenta Ajena', true, 39),
('PROFESIONALES_ALTAMENTE_CUALIF', 'Autorización Inicial de Residencia y trabajo de Profesionales Altamente Cualificados', true, 40),
('FAMILIAR_PROF_ALTAMENTE_CUALIF', 'Autorización Inicial de Residencia y trabajo de Familiar de Profesionales Altamente Cualificados', true, 41),
('RENOVACION_PROF_ALTAMENTE_CUALIF', 'Renovación Residencia y trabajo de Profesionales Altamente Cualificados', true, 42),
('RENOVACION_FAM_PROF_ALT_CUALIF', 'Renovación Residencia y trabajo de Familiar de Profesionales Altamente Cualificados', true, 43),
('TRABAJO_DURACION_DETERMINADA', 'Autorización de Residencia y trabajo por cuenta ajena (Duración determinada, alta dirección, deportistas, artistas)', true, 44),
('RESIDENCIA_TRABAJO_PROPIA', 'Autorización Inicial de Residencia y trabajo por Cuenta Propia', true, 45),
('RENOVACION_TRABAJO_PROPIA', 'Renovación de Residencia y trabajo por Cuenta Propia', true, 46),
('ARRAIGO_SOCIOLABORAL', 'Autorización de Residencia por Arraigo SocioLaboral', true, 47),
('ARRAIGO_SOCIAL', 'Autorización de Residencia por Arraigo Social', true, 48),
('ARRAIGO_SEGUNDA_OPORTUNIDAD', 'Autorización de Residencia por Arraigo Segunda Oportunidad', true, 49),
('ARRAIGO_FAMILIAR', 'Autorización de Residencia por Arraigo Familiar', true, 50),
('ARRAIGO_SOCIOFORMATIVO', 'Autorización de Residencia por Arraigo SocioFormativo', true, 51),
('PROTECCION_INTERNACIONAL', 'Autorización de Residencia por Protección Internacional', true, 52),
('VICTIMAS_VIOLENCIA_GENERO', 'Autorización de Residencia para Mujeres Víctimas de Violencia de Género', true, 53),
('LARGA_DURACION', 'Autorización de Residencia de Larga-duración', true, 54),
('LARGA_DURACION_UE', 'Autorización de Residencia de Larga-duración UE', true, 55),
('RECUPERACION_LARGA_DURACION', 'Recuperación de Residencia de Larga-duración', true, 56),
('RESIDENCIA_NACIDO_ESPANA', 'Autorización de Residencia de nacido en España (hijo de residente legal)', true, 57),
('RESIDENCIA_MENOR_NO_NACIDO_ES', 'Autorización de Residencia no lucrativa para menor no nacido en España', true, 58),
('RENOVACION_MENOR_NO_NACIDO_ES', 'Renovación de Residencia no lucrativa para menor no nacido en España', true, 59),
('MOD_ESTUDIOS_TRABAJO_AJENA', 'Modificación de situación de Estancia por Estudios a Residencia y trabajo por cuenta ajena', true, 60),
('MOD_ESTUDIOS_TRABAJO_PROPIA', 'Modificación de situación de Estancia por Estudios a Residencia y trabajo por cuenta propia', true, 61),
('MOD_ESTUDIOS_PROF_ALT_CUALIF', 'Modificación de situación de Estancia por Estudios a Residencia y trabajo de Profesionales altamente cualificados', true, 62),
('MOD_RESIDENCIA_TRABAJO_AJENA', 'Modificación de situación de Residencia a Residencia y trabajo por cuenta ajena', true, 63),
('MOD_RESIDENCIA_TRABAJO_PROPIA', 'Modificación de situación de Residencia a Residencia y trabajo por cuenta propia', true, 64),
('MOD_RESIDENCIA_PROF_ALT_CUALIF', 'Modificación de situación de Residencia a Residencia y trabajo de Profesionales Altamente Cualificados', true, 65),
('MOD_REGIMEN_COMUNITARIO_NULIDAD', 'Modificación de situación de Régimen Comunitario por nulidad del vínculo', true, 66),
('MODIFICACIONES_GENERAL', 'Modificaciones en general', true, 67),
('TARJETA_COMUNITARIA', 'Tarjeta de residencia de familiar de ciudadano de la UE (Tarjeta Comunitaria)', true, 68),
('RENOVACION_TARJETA_COMUNITARIA', 'Renovación de residencia de familiar de ciudadano de la UE (Tarjeta Comunitaria)', true, 69),
('RESIDENCIA_BUSQUEDA_EMPLEO', 'Autorización de Residencia para Búsqueda de empleo', true, 70),
('RESIDENCIA_PRACTICAS_CONTRATO', 'Autorización de Residencia para Prácticas (por contrato)', true, 71),
('NOMADA_DIGITAL_TITULAR', 'Residencia Nómada Digital - Titular', true, 72),
('NOMADA_DIGITAL_FAMILIAR', 'Residencia Nómada Digital - Por cada miembro de la familia', true, 73),
('TRANSLADO_INTEREMPRESARIAL', 'Traslado interempresarial por cada empleado', true, 74),
('PROFESIONAL_ALT_CUALIFICADO', 'Profesional altamente cualificado', true, 75),
('FAMILIAR_PROF_ALT_CUALIFICADO', 'Familiar Profesional altamente cualificado', true, 76),
('NACIONALIDAD_RESIDENCIA_MENORES', 'Nacionalidad española por residencia para menores de 14 años', true, 77),
('NACIONALIDAD_OPCION', 'Nacionalidad española por opción', true, 78),
('NACIONALIDAD_SIMPLE_PRESUNCION', 'Nacionalidad española por Valor de simple presunción', true, 79),
('NACIONALIDAD_PRESUNCION_BRASIL', 'Nacionalidad española por Valor de simple presunción + no nacional (brasileños)', true, 80),
('JURA_NACIONALIDAD', 'Jura de Nacionalidad española', true, 81),
('NACIONALIDAD_ORIGEN', 'Nacionalidad española de origen', true, 82),
('INSCRIPCION_NACIMIENTO_FUERA_PLAZO', 'Inscripción de nacimiento fuera del plazo legal', true, 83),
('INSCRIPCION_NACIMIENTO_DESCENDIENTES', 'Inscripción de nacimiento fuera de plazo (descendientes de españoles)', true, 84),
('INSCRIPCION_NACIMIENTO_EXTRANJERO', 'Inscripción de nacimiento producido en el extranjero', true, 85),
('RECURSO_NACIONALIDAD', 'Recurso de nacionalidad española', true, 86),
('OUTRO', 'Outro', true, 99)
ON CONFLICT (code) DO NOTHING;

-- Add service_type_id column to leads for linking to the expanded service_types table
ALTER TABLE leads ADD COLUMN IF NOT EXISTS service_type_id uuid REFERENCES service_types(id);

-- Backfill existing leads
UPDATE leads l
SET service_type_id = st.id
FROM service_types st
WHERE l.service_type_id IS NULL
AND l.service_interest::text = st.code;
