
-- Limpeza de dados operacionais de clientes (preserva usuários, configs, KB, templates, serviços, bancos)
TRUNCATE TABLE
  public.nps_surveys,
  public.payment_reminders,
  public.contract_reminders,
  public.document_reminders,
  public.huellas_reminders,
  public.initial_contact_reminders,
  public.requirement_reminders,
  public.tie_pickup_reminders,
  public.commissions,
  public.invoices,
  public.cash_flow,
  public.payments,
  public.contract_costs,
  public.contract_notes,
  public.contract_beneficiaries,
  public.contract_leads,
  public.beneficiary_titular_links,
  public.contracts,
  public.requirements_from_authority,
  public.service_documents,
  public.generated_documents,
  public.documents,
  public.case_notes,
  public.service_cases,
  public.tasks,
  public.notifications,
  public.interactions,
  public.portal_messages,
  public.mensagens_cliente,
  public.n8n_chat_histories,
  public.customer_chat_context,
  public.chat_routing_logs,
  public.customer_sector_pending_items,
  public.contact_data_suggestions,
  public.reactivation_resolutions,
  public.opportunities,
  public.lead_intake,
  public.leads,
  public.contacts,
  public.message_dedup,
  public.whatsapp_template_logs,
  public.webhook_logs,
  public.log_webhooks_falhados,
  public.audit_logs
RESTART IDENTITY CASCADE;
