// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Lovable runtime does not reliably provide Vite env vars in the preview/hosted build.
// Use your Supabase project constants directly.
export const SUPABASE_PROJECT_ID = "xdnliyuogkoxckbesktx";
export const SUPABASE_URL = "https://xdnliyuogkoxckbesktx.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkbmxpeXVvZ2tveGNrYmVza3R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU4MDE1NDMsImV4cCI6MjA4MTM3NzU0M30.qYYrZd1l-IkBjPUZ0w9jTqM-ChaghpAZrTqlri3hnbw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
});

/**
 * Renova o token apenas quando ele está perto de expirar.
 * Chamar `refreshSession()` sem necessidade dispara `TOKEN_REFRESHED`, o que
 * remontava telas inteiras (e derrubava editores com rascunho não salvo).
 */
export async function ensureFreshSession(thresholdMs = 120_000): Promise<void> {
  try {
    const { data: { session } } = await supabase.auth.getSession();
    if (!session) return;
    const expiresAt = session.expires_at ? session.expires_at * 1000 : 0;
    if (expiresAt - Date.now() < thresholdMs) {
      await supabase.auth.refreshSession();
    }
  } catch (e) {
    console.warn('Session refresh skipped:', e);
  }
}

// Proactively refresh session when tab regains focus to prevent JWT expired errors
let isRefreshing = false;
const handleVisibilityChange = async () => {
  if (document.visibilityState === 'visible' && !isRefreshing) {
    isRefreshing = true;
    try {
      await ensureFreshSession();
    } finally {
      isRefreshing = false;
    }
  }
};


if (typeof document !== 'undefined') {
  document.addEventListener('visibilitychange', handleVisibilityChange);
}
